### ISSUE TITLE
consider eliminating repositories that created by just clicking "new repository"

### ISSUE THREAD

**Issue by haolian9** [yutkat/new-neovim-plugin-rss#13]
hi! i found there is a kind of new repositories that only contains three files:
.gitignore, LICENSE, README.md, it's in fact empty, and worth not to contain it in the rss list.

i think them are created just by clicking the `new repository` + `add a README file` + `add .gitignore` + `choose a license`.

i checked the response of 'search repository' api, it seems there is no field we can use to filter them;

yet i think we can shallow clone them, like `git clone --depth 1`, and check the tracked files manually, of course it requires much more network traffic. luckily the api tells the size of a repository, so for a really large repository, maybe we can treat it as non-empty.

so do you have any other ideas about this? and is it worth it?

**Comment by yutkat** [comment]
Thanks for your feedback, I'm glad to hear that. I felt that was too noisy lately, so I've fixed the filter. https://github.com/yutkat/new-neovim-plugin-rss/commit/8f0e178e5909d98e5ed840a93be683a5a3e46a38

And if you want clean RSS, you might subscribe to this one.
https://github.com/yutkat/new-neovim-plugin-with-category-rss

**Comment by haolian9** [comment]
wow, great to know there is a lightweight solution, just learnt about `gh api /repos/{x}/contents`.
and thanks for creating this rss source, i really enjoy it.
